# Generated by Django 4.0.1 on 2022-01-27 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nombre_de_usuario',
            new_name='username',
        ),
    ]
