# Generated by Django 4.0 on 2022-01-19 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0002_comentario_publicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='publicacion',
        ),
    ]
