# Generated by Django 4.0.1 on 2022-01-23 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0003_remove_comentario_publicacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clave',
            new_name='clave1',
        ),
        migrations.AddField(
            model_name='usuario',
            name='clave2',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
