# Generated by Django 4.0.1 on 2022-01-30 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0004_rename_fecha_publi_publicacion_fecha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publicacion',
            old_name='fecha',
            new_name='fecha_publi',
        ),
    ]
