# Generated by Django 4.0.1 on 2022-01-30 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0005_rename_fecha_publicacion_fecha_publi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LECTOR', 'Lector'), ('AUTOR', 'Autor')], default='', max_length=6),
        ),
    ]
