# Generated by Django 4.0.1 on 2022-01-23 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0005_remove_usuario_clave2'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave2',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
