# Generated by Django 4.0.1 on 2022-01-23 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0006_usuario_clave2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='clave1',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='clave2',
            new_name='password2',
        ),
    ]
