# Generated by Django 4.0.1 on 2022-02-02 19:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0006_alter_usuario_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='noticia',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
