# Generated by Django 4.0.1 on 2022-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0007_rename_clave1_usuario_password1_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
