# Generated by Django 4.0.1 on 2022-01-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0008_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=12)),
                ('password2', models.CharField(max_length=12)),
                ('tipo', models.CharField(default='', max_length=6)),
            ],
        ),
    ]
