# Generated by Django 4.0.1 on 2022-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PlayApp', '0008_comentario_publicacion_alter_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('LECTOR', 'Lector'), ('AUTOR', 'Autor')], default='LECTOR', max_length=6),
        ),
    ]
